### PR TITLE
Utility function added to create a cylindrical container from boxes

### PR DESCRIPTION
**Pull request by armanpazouki**
Adding a cylindrical container from boxes. The ends can be cylinders or boxes; the latter behaves better in parallel.

### CODE REVIEW

**Comment by andrewseidl** [comment]
Could you run clang-format on the new code? The indentation doesn't look quite right.

**Comment by armanpazouki** [comment]
will commit the formatted code. closing this request for now.

**Comment by andrewseidl** [comment]
No need to close, just `git add [files]`, `git commit --amend`, and then force push to your fork.

**Comment by armanpazouki** [comment]
I had already created a new commit. Can it be transferred under this same pull request?

**Comment by andrewseidl** [comment]
Do an interactive rebase `git rebase -i` and squash the new commit into the first one.

New commits to the same branch are automatically added to the pull request. In this case, any new commits you (force) push to `develop` in your fork will be added/replaced.

**Pull request merged**
