### PR TITLE
Ppt script demo m113

### PR DESCRIPTION
**Pull request by jcmadsen**
adding the output data and plotting capabilities needed to validate test_M113 against reported values in report by Shabana, Wallin.

### CODE REVIEW

**Comment by jcmadsen** [comment]
looks like Clang doesn't like C++11 lambda functions, so I'll remove that

**Comment by andrewseidl** [comment]
> looks like Clang doesn't like C++11 lambda functions

Chrono itself does not currently support C++11, though I'm hoping we can change that for the next release.

I'm a bit surprised that GCC accepted the lambda fn...

**Comment by jcmadsen** [comment]
Tossed the lambda function, combined that commit into the previous one.
What will surprise you most is that VS 2013 has decent C++ 11 support.

**Comment by andrewseidl** [comment]
Please run [`clang-format`](http://clang.llvm.org/docs/ClangFormat.html#visual-studio-integration) on the modified C++ files - it looks like you're mixing 2-space and 4-space indents (Chrono uses the latter).

Is all the dead code necessary/can it be removed? For example, [trackVehicle/TrackVehicleM113.cpp#L612-L675](https://github.com/jcmadsen/chrono/blob/322a8104558c6cfaf233bfb6446fd0460361191c/src/demos/trackVehicle/subsys/trackVehicle/TrackVehicleM113.cpp#L612-L675)

@rserban: How does everything look to you?

**Comment by rserban** [comment]
Looks fine to me.  As long as these pull requests only concern files in the demos/trackVehicle folder, the only concerns are to keep number of commits to the necessary minimum and to commit clean code.  All this functionality will eventually be superseded by the Chrono::Vehicle track support, at which point this entire folder in chrono/demos will be removed (hence the desire to keep the number of commits to a minimum).

**Comment by jcmadsen** [comment]
that code is not dead, I just haven't gotten it working for an arbitrary number of runningGear systems.
And I though 2 space indents were being used, but I'll switch to 4.

**Pull request merged**
